/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.AcessScreen.AccessingScreen;
import View.AcessScreen.accessRecepcao;
import View.AcessScreen.accessTi;
import Model.authenticateLogin;
import Controller.dadosLogin;
import View.AcessScreen.accessAlmoxarifado;
import View.AcessScreen.accessEnfermaria;
import View.AcessScreen.accessFarmacia;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author uande
 */
public class telaLogin extends javax.swing.JFrame {

    /**
     * Creates new form telaLogin
     */
    public telaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logEntrar = new javax.swing.JButton();
        logSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");

        logUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Senha:");

        jLabel2.setText("Usuário:");

        logEntrar.setText("Entrar");
        logEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(logEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(logSenha)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        setBounds(460, 200, 416, 308);
    }// </editor-fold>//GEN-END:initComponents

    private void logUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logUsuarioActionPerformed

    private void logEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logEntrarActionPerformed
        try {
            String usuario;
            String senha;

            usuario=logUsuario.getText();
            senha=logSenha.getText();

            dadosLogin objlogin = new dadosLogin();
            objlogin.setUsuario(usuario);
            objlogin.setSenha(senha);
            
            authenticateLogin objusuario = new authenticateLogin();
                  
            ResultSet rsauthenticateLogin = objusuario.autenticacaoUsuario(objlogin);
              
            ResultSet   rs =  objusuario.checkSector(objlogin);
           
           if (rsauthenticateLogin.next()){
            while(rs.next()){
                String   setor=rs.getString("setor").toString().trim();               
                
                    if(setor.equals("TI")){
                        dadosLogin objpes = new dadosLogin();
                         
                        
                        AccessingScreen accessingscreen = new accessTi();
                        accessingscreen.acessScreen();
                        dispose();
                    }
                    if(setor.equals("Recepção")){
                        dadosLogin objpes = new dadosLogin();
                         
                        
                        AccessingScreen accessingscreen = new accessRecepcao();
                        accessingscreen.acessScreen();
                        dispose();
                    
                }
                    if(setor.equals("Enfermaria")){
                        dadosLogin objpes = new dadosLogin();
                         
                        
                        AccessingScreen accessingscreen = new accessEnfermaria();
                        accessingscreen.acessScreen();
                        dispose();
                    
                }
                    if(setor.equals("Farmacia")){
                        dadosLogin objpes = new dadosLogin();
                         
                        
                        AccessingScreen accessingscreen = new accessFarmacia();
                        accessingscreen.acessScreen();
                        dispose();
                    
                }
                    if(setor.equals("Almoxarifado")){
                        dadosLogin objpes = new dadosLogin();
                         
                        
                        AccessingScreen accessingscreen = new accessAlmoxarifado();
                        accessingscreen.acessScreen();
                        dispose();
                    
                }
                
            }
            }
            else{
                JOptionPane.showInternalMessageDialog(null,"Usuário ou Senha Inválida.");
            }

        } catch (SQLException erro) {
            JOptionPane.showInternalMessageDialog(null,"telaLogin :"+ erro);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_logEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
               }
            }
    } 
    catch (UnsupportedLookAndFeelException e) {
       // handle exception
    }
    catch (ClassNotFoundException e) {
       // handle exception
    }
    catch (InstantiationException e) {
       // handle exception
    }
    catch (IllegalAccessException e) {
       // handle exception
    }
                new telaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logEntrar;
    private javax.swing.JPasswordField logSenha;
    private javax.swing.JTextField logUsuario;
    // End of variables declaration//GEN-END:variables
}
