/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;


import Controller.dadosFarmacia;
import Model.query;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author uande
 */
public class telaFarmaciaFarmaciaConsulta extends javax.swing.JInternalFrame {
    dadosFarmacia objpes= new dadosFarmacia();
    
    public static boolean farmaciaProdutos;
    /**
     * Creates new form telaConsulta
     */
    public telaFarmaciaFarmaciaConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        farVariavel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        farArgumento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        conTabela = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        conSair = new javax.swing.JButton();
        novoProduto = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        farVariavel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Produtos", " " }));

        jLabel1.setText("Consultar por :");

        farArgumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                farArgumentoKeyReleased(evt);
            }
        });

        conTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produtos"
            }
        ));
        jScrollPane1.setViewportView(conTabela);
        if (conTabela.getColumnModel().getColumnCount() > 0) {
            conTabela.getColumnModel().getColumn(0).setMinWidth(100);
            conTabela.getColumnModel().getColumn(0).setPreferredWidth(40);
            conTabela.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel2.setText("Argumento:");

        conSair.setText("Sair");
        conSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conSairActionPerformed(evt);
            }
        });

        novoProduto.setText("Novo Produto");
        novoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(farVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(farArgumento, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(novoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conSair, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(farVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farArgumento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(novoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conSair, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setBounds(0, 0, 907, 468);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
        
        telaFarmaciaFarmaciaConsulta.farmaciaProdutos= false;
        DefaultTableModel mp1  = (DefaultTableModel) conTabela.getModel();
        int l=mp1.getRowCount();
        
            if(l>0){
                    while(l>0){
                ((DefaultTableModel) conTabela.getModel()).removeRow(l-1);
                              l--;
            }
            }
            try{
                ResultSet   rs=  query.loadTableFarmacia();
                DefaultTableModel mp  = (DefaultTableModel) conTabela.getModel();
                while(rs.next()){
                    String   Coluna0=rs.getString("cod").toString().trim();
                    String   Coluna1=rs.getString("produto").toString().trim();
      
                    mp.addRow(new String[]{Coluna0,Coluna1});
                    
                }
            }
                catch(SQLException erro){
                        JOptionPane.showMessageDialog(this, "Ocorreu um erro: "+erro,"Preencher Item",2);
                        }
                tamanhocolunas();
                conTabela.setAutoCreateRowSorter(true);
            
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
         
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void conSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conSairActionPerformed
        
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_conSairActionPerformed

    private void farArgumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_farArgumentoKeyReleased
       String tipo=" ";
       String escolha=farVariavel.getSelectedItem().toString().trim();
       

       if(escolha.equals("Produtos")){
           tipo="  "+"produto";
       }

       
       String arg=farArgumento.getText().toUpperCase();
       
        DefaultTableModel mp1  = (DefaultTableModel) conTabela.getModel();
        int l=mp1.getRowCount();
       
       if(l>0){
                    while(l>0){
                ((DefaultTableModel) conTabela.getModel()).removeRow(l-1);
                              l--;
            }
            }
       
            try{
                ResultSet   rs=  query.loadTableFarmacia(tipo,  arg);
                DefaultTableModel mp  = (DefaultTableModel) conTabela.getModel();
                while(rs.next()){
                    String   Coluna0=rs.getString("cod").toString().trim();
                    String   Coluna1=rs.getString("produto").toString().trim();


                    
                    mp.addRow(new String[]{Coluna0,Coluna1});
                    
                }
            }
                catch(SQLException erro){
                        JOptionPane.showMessageDialog(this, "Ocorreu um erro: "+erro,"Preencher Item",2);
                        }
                tamanhocolunas();
                conTabela.setAutoCreateRowSorter(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_farArgumentoKeyReleased

    private void novoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoProdutoActionPerformed
        if(farmaciaProdutos==false){ 
        telaFarmaciaFarmaciaCadastro obj = new telaFarmaciaFarmaciaCadastro();
        telaTIPrincipal.telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_novoProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conSair;
    private javax.swing.JTable conTabela;
    private javax.swing.JTextField farArgumento;
    private javax.swing.JComboBox<String> farVariavel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novoProduto;
    // End of variables declaration//GEN-END:variables
public void tamanhocolunas(){
conTabela.getColumnModel().getColumn(0).setMinWidth(100);
conTabela.getColumnModel().getColumn(1).setMinWidth(250);
}


}



