/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;



/**
 *
 * @author uande
 */
public class telaAlmoxarifadoPrincipal extends javax.swing.JFrame {
    
    public static boolean almcadastroProdutos;
    public static boolean almexibirProdutos;
    public static boolean almpedirProdutos;
    public static boolean almsolicitacaoProdutos;

    /**
     * Creates new form pjtPrincipal
     */
    public telaAlmoxarifadoPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        telaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastrarprodutos = new javax.swing.JMenuItem();
        exibirprodutos = new javax.swing.JMenuItem();
        pedirprodutos = new javax.swing.JMenuItem();
        produtossolicitados = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout telaPrincipalLayout = new javax.swing.GroupLayout(telaPrincipal);
        telaPrincipal.setLayout(telaPrincipalLayout);
        telaPrincipalLayout.setHorizontalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        telaPrincipalLayout.setVerticalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Almoxarifado");

        cadastrarprodutos.setText("Cadastrar Produtos");
        cadastrarprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarprodutosActionPerformed(evt);
            }
        });
        jMenu1.add(cadastrarprodutos);

        exibirprodutos.setText("Exibir Produtos");
        exibirprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirprodutosActionPerformed(evt);
            }
        });
        jMenu1.add(exibirprodutos);

        pedirprodutos.setText("Pedir Produtos");
        pedirprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirprodutosActionPerformed(evt);
            }
        });
        jMenu1.add(pedirprodutos);

        produtossolicitados.setText("Produtos Solicitados");
        produtossolicitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtossolicitadosActionPerformed(evt);
            }
        });
        jMenu1.add(produtossolicitados);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
       
        telaAlmoxarifadoPrincipal.almexibirProdutos=false;
        telaAlmoxarifadoPrincipal.almpedirProdutos=false;
        telaAlmoxarifadoPrincipal.almcadastroProdutos=false;
        telaAlmoxarifadoPrincipal.almsolicitacaoProdutos=false;
        

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void cadastrarprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarprodutosActionPerformed
         if(almcadastroProdutos==false){ 
        telaAlmoxarifadoAlmoxarifadoCadastro obj = new telaAlmoxarifadoAlmoxarifadoCadastro();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarprodutosActionPerformed

    private void exibirprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirprodutosActionPerformed
        if(almcadastroProdutos==false){ 
        telaAlmoxarifadoAlmoxarifadoConsulta obj = new telaAlmoxarifadoAlmoxarifadoConsulta();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_exibirprodutosActionPerformed

    private void pedirprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirprodutosActionPerformed
        if(almpedirProdutos==false){ 
        telaAlmoxarifadoAlmoxarifadoPedir obj = new telaAlmoxarifadoAlmoxarifadoPedir();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_pedirprodutosActionPerformed

    private void produtossolicitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtossolicitadosActionPerformed
        if(almsolicitacaoProdutos==false){ 
        telaAlmoxarifadoAlmoxarifadoPedidos obj = new telaAlmoxarifadoAlmoxarifadoPedidos();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_produtossolicitadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarprodutos;
    private javax.swing.JMenuItem exibirprodutos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem pedirprodutos;
    private javax.swing.JMenuItem produtossolicitados;
    public static javax.swing.JDesktopPane telaPrincipal;
    // End of variables declaration//GEN-END:variables

}
