/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;




/**
 *
 * @author uande
 */
public class telaRecepcaoPrincipal extends javax.swing.JFrame {
    public static boolean cadastro;
    public static boolean consulta;
    public static boolean almpedirProdutos;

    
    /**
     * Creates new form pjtPrincipal
     */
    public telaRecepcaoPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Consultar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        recpedirproddutos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout telaPrincipalLayout = new javax.swing.GroupLayout(telaPrincipal);
        telaPrincipal.setLayout(telaPrincipalLayout);
        telaPrincipalLayout.setHorizontalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        telaPrincipalLayout.setVerticalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        cadastrar.setText("Cadastrar Paciente");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(cadastrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultar");

        Consultar.setText("Consultar Paciente");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        jMenu2.add(Consultar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Almoxarifado");

        recpedirproddutos.setText("Pedir Produtos");
        recpedirproddutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recpedirproddutosActionPerformed(evt);
            }
        });
        jMenu3.add(recpedirproddutos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
        telaRecepcaoPrincipal.cadastro=false;
        telaRecepcaoPrincipal.consulta=false;
        telaRecepcaoPrincipal.almpedirProdutos=false;
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        if(cadastro==false){ 
        telaRecepcaoCadastro obj = new telaRecepcaoCadastro();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        if(consulta==false){ 
        telaRecepcaoConsulta obj = new telaRecepcaoConsulta();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarActionPerformed

    private void recpedirproddutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recpedirproddutosActionPerformed
        if(almpedirProdutos==false){ 
        telaRecepcaoAlmoxarifadoPedir obj = new telaRecepcaoAlmoxarifadoPedir();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_recpedirproddutosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Consultar;
    private javax.swing.JMenuItem cadastrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem recpedirproddutos;
    public static javax.swing.JDesktopPane telaPrincipal;
    // End of variables declaration//GEN-END:variables
}
