/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.dadosProntuario;
import Model.addEdit;
import Model.delete;
import Model.search;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author uande
 */
public class telaTIProntuario extends javax.swing.JInternalFrame {

    int acao;   
    
    dadosProntuario objpes =  new dadosProntuario();
    addEdit  AE;
    delete Del;
    search Sea;
    /**
     * Creates new form telaProntuario
     */
    public telaTIProntuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        proMes = new javax.swing.JTextField();
        proDia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        proAno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        proHora = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        proOrientacao = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        proInformacao = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        proAvaliacao = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        proNovo = new javax.swing.JButton();
        proSalvar = new javax.swing.JButton();
        proEditar = new javax.swing.JButton();
        proCancelar = new javax.swing.JButton();
        proSair = new javax.swing.JButton();
        proCpf = new javax.swing.JFormattedTextField();
        proVerificar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        proNome.setEnabled(false);

        jLabel1.setText("Nome Completo:");

        jLabel2.setText("CPF:");

        proMes.setEnabled(false);

        proDia.setEnabled(false);
        proDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proDiaActionPerformed(evt);
            }
        });

        jLabel3.setText("/");

        jLabel4.setText("/");

        proAno.setEnabled(false);
        proAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proAnoActionPerformed(evt);
            }
        });

        jLabel5.setText("Data:");

        jLabel6.setText("Hora:");

        try {
            proHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        proHora.setEnabled(false);
        proHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proHoraActionPerformed(evt);
            }
        });

        proOrientacao.setColumns(20);
        proOrientacao.setLineWrap(true);
        proOrientacao.setRows(5);
        proOrientacao.setEnabled(false);
        jScrollPane1.setViewportView(proOrientacao);

        proInformacao.setColumns(20);
        proInformacao.setLineWrap(true);
        proInformacao.setRows(5);
        proInformacao.setEnabled(false);
        jScrollPane2.setViewportView(proInformacao);

        proAvaliacao.setColumns(20);
        proAvaliacao.setLineWrap(true);
        proAvaliacao.setRows(5);
        proAvaliacao.setEnabled(false);
        jScrollPane3.setViewportView(proAvaliacao);

        jLabel7.setText("Informações Básicas:");

        jLabel8.setText("Avaliação:");

        jLabel9.setText("Orientações:");

        proNovo.setText("Novo");
        proNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proNovoActionPerformed(evt);
            }
        });

        proSalvar.setText("Salvar");
        proSalvar.setEnabled(false);
        proSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proSalvarActionPerformed(evt);
            }
        });

        proEditar.setText("Editar");
        proEditar.setEnabled(false);
        proEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proEditarActionPerformed(evt);
            }
        });

        proCancelar.setText("Cancelar");
        proCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proCancelarActionPerformed(evt);
            }
        });

        proSair.setText("Sair");
        proSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proSairActionPerformed(evt);
            }
        });

        try {
            proCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        proCpf.setEnabled(false);

        proVerificar.setText("...");
        proVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(proCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(proEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(proSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(proNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(proSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(proDia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(proMes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(proAno, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(proHora, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(proNome, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(proCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(proVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(proAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(proNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(proSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(proEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(proCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(proSair, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        setBounds(0, 0, 600, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void proAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proAnoActionPerformed

    private void proHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proHoraActionPerformed

    private void proDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proDiaActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        telaEnfermariaPrincipal.cadastro=true;
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void proSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proSairActionPerformed
        telaEnfermariaPrincipal.cadastro=false;
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_proSairActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        telaEnfermariaPrincipal.cadastro=false;
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void proSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proSalvarActionPerformed
        objpes= new dadosProntuario();
        preencher_objetos();
        try {
            AE = new addEdit();
            
                    if(acao==1){
                        AE.IncluirProntuario(objpes);
                        JOptionPane.showMessageDialog(this, "Salvo com sucesso !");
                        Salvar();
                    }  
                    if(acao==2){
                        objpes.setCpf(proCpf.getText());
                        if(AE.EditarProntuario(objpes)){
                            JOptionPane.showMessageDialog(this, "Alterado com sucesso !");
                            Salvar();
                        }
                        
                    }
        }catch(SQLException error){
           JOptionPane.showMessageDialog (this,"Operação Não Realizada."+error.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_proSalvarActionPerformed

    private void proNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proNovoActionPerformed
        acao=1;
        Novo();
        // TODO add your handling code here:
    }//GEN-LAST:event_proNovoActionPerformed

    private void proEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proEditarActionPerformed
        acao=2;
        Editar();
        // TODO add your handling code here:
    }//GEN-LAST:event_proEditarActionPerformed

    private void proCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proCancelarActionPerformed
        Cancelar();
        // TODO add your handling code here:
    }//GEN-LAST:event_proCancelarActionPerformed

    private void proVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proVerificarActionPerformed
        objpes= new dadosProntuario();
        objpes.setCpf(proCpf.getText());
                    Sea=  new  search();
                    try{
                        
                        if(Sea.SearchProntuario(objpes)){
                            if((objpes !=  null)){
                                pesquisa();
                            }
                                
                            }
                        }catch(SQLException erro){
                            JOptionPane.showMessageDialog(this,"Erro ao Pesquisar"+  erro.getMessage());
                        }
        // TODO add your handling code here:
    }//GEN-LAST:event_proVerificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JTextField proAno;
    private javax.swing.JTextArea proAvaliacao;
    private javax.swing.JButton proCancelar;
    private static javax.swing.JFormattedTextField proCpf;
    private static javax.swing.JTextField proDia;
    private javax.swing.JButton proEditar;
    private javax.swing.JFormattedTextField proHora;
    private javax.swing.JTextArea proInformacao;
    private static javax.swing.JTextField proMes;
    private javax.swing.JTextField proNome;
    private javax.swing.JButton proNovo;
    private javax.swing.JTextArea proOrientacao;
    private javax.swing.JButton proSair;
    private javax.swing.JButton proSalvar;
    private javax.swing.JButton proVerificar;
    // End of variables declaration//GEN-END:variables
public void preencher_objetos(){
    
            objpes.setNome(proNome.getText().trim());
            objpes.setDia(proDia.getText());
            objpes.setMes(proMes.getText());
            objpes.setAno(proAno.getText());
            objpes.setHora(proHora.getText());
            objpes.setCpf(proCpf.getText());
            objpes.setInformacao(proInformacao.getText());
            objpes.setAvaliacao(proAvaliacao.getText());
            objpes.setOrientacao(proOrientacao.getText());
            
    }
        
   public void pesquisa(){
      
          proNome.setText(objpes.getNome().trim());
          proDia.setText(objpes.getDia());       
          proMes.setText(objpes.getMes().trim()); 
          proAno.setText(objpes.getAno().trim()); 
          proHora.setText(objpes.getHora().trim()); 
          proCpf.setText(objpes.getCpf().trim()); 
          proInformacao.setText(objpes.getInformacao().trim()); 
          proAvaliacao.setText(objpes.getAvaliacao().trim()); 
          proOrientacao.setText(objpes.getOrientacao().trim()); 
          proEditar.setEnabled(true);
   } 
    

    public void Novo(){
        
        proNome.setEnabled(true);
        proDia.setEnabled(true);
        proMes.setEnabled(true);
        proAno.setEnabled(true);
        proHora.setEnabled(true);
        proCpf.setEnabled(true);
        proInformacao.setEnabled(true);
        proAvaliacao.setEnabled(true);
        proOrientacao.setEnabled(true);
        proSalvar.setEnabled(true);
        proEditar.setEnabled(true);
        
        proNome.setText("");
        proDia.setText("");   
        proMes.setText("");   
        proAno.setText("");
        proHora.setText("");
        proCpf.setText("");
        proInformacao.setText("");
        proAvaliacao.setText("");
        proOrientacao.setText("");
        
    }

    public void Cancelar(){
        
        proNome.setEnabled(false);
        proDia.setEnabled(false);
        proMes.setEnabled(false);
        proAno.setEnabled(false);
        proHora.setEnabled(false);
        proCpf.setEnabled(false);
        proInformacao.setEnabled(false);
        proAvaliacao.setEnabled(false);
        proOrientacao.setEnabled(false);
        proSalvar.setEnabled(false);
        proEditar.setEnabled(false);
        proNome.setText("");
        proDia.setText("");   
        proMes.setText("");   
        proAno.setText("");
        proHora.setText("");
        proCpf.setText("");
        proInformacao.setText("");
        proAvaliacao.setText("");
        proOrientacao.setText("");
    }
public void Editar(){
    
         proNome.setEnabled(true);
        proDia.setEnabled(true);
        proMes.setEnabled(true);
        proAno.setEnabled(true);
        proHora.setEnabled(true);
        proCpf.setEnabled(true);
        proInformacao.setEnabled(true);
        proAvaliacao.setEnabled(true);
        proOrientacao.setEnabled(true);
        proSalvar.setEnabled(true);
        proEditar.setEnabled(true);
        
}
public void Salvar(){
    
        proNome.setEnabled(false);
        proDia.setEnabled(false);
        proMes.setEnabled(false);
        proAno.setEnabled(false);
        proHora.setEnabled(false);
        proCpf.setEnabled(false);
        proInformacao.setEnabled(false);
        proAvaliacao.setEnabled(false);
        proOrientacao.setEnabled(false);
        proSalvar.setEnabled(false);
        proEditar.setEnabled(true);

}
public static void recebecpf(dadosProntuario objpes){
    proCpf.setText(objpes.getCpf());
    proCpf.requestFocus();
    proDia.setText(objpes.getDia());
    proDia.requestFocus();
    proMes.setText(objpes.getMes());
    proMes.requestFocus();
    proAno.setText(objpes.getAno());
    proAno.requestFocus();
}

}

