/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.dadosEnfermaria;
import Model.addEdit;
import Model.delete;
import Model.search;
import static View.telaEnfermariaPrincipal.telaPrincipal;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author uande
 */
public class telaEnfermariaEnfermaria extends javax.swing.JInternalFrame {

     int acao;   
    
    dadosEnfermaria objpes =  new dadosEnfermaria();
    addEdit  AE;
    search Sea;
    public static boolean prontuario;
    public telaEnfermariaEnfermaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        enfNome = new javax.swing.JTextField();
        enfVerificar = new javax.swing.JButton();
        enfRaca = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        enfSexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        enfTiposanguineo = new javax.swing.JComboBox<>();
        enfSalvar = new javax.swing.JButton();
        enfEditar = new javax.swing.JButton();
        enfNovo = new javax.swing.JButton();
        enfSair = new javax.swing.JButton();
        enfCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        enfRemediobox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        enfCancertexto = new javax.swing.JTextArea();
        enfCancerbox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        enfDiabetetexto = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        enfRemediotexto = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        enfCronicatexto = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        enfHipertensaotexto = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        enfCardiacatexto = new javax.swing.JTextArea();
        enfStatus = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        enfAlergiatexto = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        enfCirurgiatexto = new javax.swing.JTextArea();
        enfHipertensaobox = new javax.swing.JComboBox<>();
        enfDiabetebox = new javax.swing.JComboBox<>();
        enfCardiacabox = new javax.swing.JComboBox<>();
        enfCirurgiabox = new javax.swing.JComboBox<>();
        enfCronicabox = new javax.swing.JComboBox<>();
        enfAlergiabox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        enfData = new javax.swing.JFormattedTextField();
        enfAltura = new javax.swing.JFormattedTextField();
        enfProntuario = new javax.swing.JButton();
        enfCpf = new javax.swing.JFormattedTextField();

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jLabel13.setText("Toma algum rémedio ? Se sim qual?");

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        enfNome.setEnabled(false);
        enfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfNomeActionPerformed(evt);
            }
        });

        enfVerificar.setText("Verificar");
        enfVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfVerificarActionPerformed(evt);
            }
        });

        enfRaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Amarelo(a)", "Branco(a)", "Indígena", "Negro(a)", "Pardo(a)" }));
        enfRaca.setEnabled(false);

        jLabel3.setText("Raça:");

        enfSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Masculino", "Feminino" }));
        enfSexo.setEnabled(false);

        jLabel4.setText("Sexo:");

        enfTiposanguineo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        enfTiposanguineo.setEnabled(false);
        enfTiposanguineo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfTiposanguineoActionPerformed(evt);
            }
        });

        enfSalvar.setText("Salvar");
        enfSalvar.setEnabled(false);
        enfSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfSalvarActionPerformed(evt);
            }
        });

        enfEditar.setText("Editar");
        enfEditar.setEnabled(false);
        enfEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfEditarActionPerformed(evt);
            }
        });

        enfNovo.setText("Novo");
        enfNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfNovoActionPerformed(evt);
            }
        });

        enfSair.setText("Sair");
        enfSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfSairActionPerformed(evt);
            }
        });

        enfCancelar.setText("Cancelar");
        enfCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo Sanguineo:");

        jLabel6.setText("Altura:");

        enfRemediobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Não", "Sim" }));
        enfRemediobox.setEnabled(false);

        enfCancertexto.setColumns(20);
        enfCancertexto.setLineWrap(true);
        enfCancertexto.setRows(5);
        enfCancertexto.setEnabled(false);
        jScrollPane1.setViewportView(enfCancertexto);

        enfCancerbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Não", "Sim", "Familiar" }));
        enfCancerbox.setEnabled(false);

        enfDiabetetexto.setColumns(20);
        enfDiabetetexto.setLineWrap(true);
        enfDiabetetexto.setRows(5);
        enfDiabetetexto.setEnabled(false);
        jScrollPane2.setViewportView(enfDiabetetexto);

        enfRemediotexto.setColumns(20);
        enfRemediotexto.setLineWrap(true);
        enfRemediotexto.setRows(5);
        enfRemediotexto.setEnabled(false);
        jScrollPane3.setViewportView(enfRemediotexto);

        enfCronicatexto.setColumns(20);
        enfCronicatexto.setLineWrap(true);
        enfCronicatexto.setRows(5);
        enfCronicatexto.setEnabled(false);
        jScrollPane4.setViewportView(enfCronicatexto);

        enfHipertensaotexto.setColumns(20);
        enfHipertensaotexto.setLineWrap(true);
        enfHipertensaotexto.setRows(5);
        enfHipertensaotexto.setEnabled(false);
        jScrollPane6.setViewportView(enfHipertensaotexto);

        enfCardiacatexto.setColumns(20);
        enfCardiacatexto.setLineWrap(true);
        enfCardiacatexto.setRows(5);
        enfCardiacatexto.setEnabled(false);
        jScrollPane7.setViewportView(enfCardiacatexto);

        enfStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Em atendimento", "Não esta mais em atendimento" }));
        enfStatus.setEnabled(false);

        enfAlergiatexto.setColumns(20);
        enfAlergiatexto.setLineWrap(true);
        enfAlergiatexto.setRows(5);
        enfAlergiatexto.setEnabled(false);
        jScrollPane8.setViewportView(enfAlergiatexto);

        enfCirurgiatexto.setColumns(20);
        enfCirurgiatexto.setLineWrap(true);
        enfCirurgiatexto.setRows(5);
        enfCirurgiatexto.setEnabled(false);
        jScrollPane9.setViewportView(enfCirurgiatexto);

        enfHipertensaobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Não", "Sim", "Familiar" }));
        enfHipertensaobox.setEnabled(false);

        enfDiabetebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Não", "Sim", "Familiar" }));
        enfDiabetebox.setEnabled(false);

        enfCardiacabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Não", "Sim", "Familiar" }));
        enfCardiacabox.setEnabled(false);

        enfCirurgiabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Não", "Sim" }));
        enfCirurgiabox.setEnabled(false);

        enfCronicabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Não", "Sim" }));
        enfCronicabox.setEnabled(false);

        enfAlergiabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Não", "Sim" }));
        enfAlergiabox.setEnabled(false);

        jLabel7.setText("Toma algum rémedio, Se sim qual:");

        jLabel23.setText("Nome Completo:");

        jLabel24.setText("Data de Nascimento:");

        jLabel25.setText("CPF:");

        jLabel26.setText("Status:");

        jLabel8.setText("Tem câncer ou alguem da familia tem:");

        jLabel9.setText("Tem hipertesão ou alguem da familia tem:");

        jLabel10.setText("Já fez alguma cirurgia:");

        jLabel11.setText("Tem diabete ou alguem da familia tem:");

        jLabel12.setText("Tem alguma doença cardiaca ou alguem ta familia tem:");

        jLabel14.setText("Tem alguma doença cronica ou deficiencia:");

        jLabel15.setText("Tem alguma alergia:");

        try {
            enfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        enfData.setEnabled(false);

        try {
            enfAltura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        enfAltura.setEnabled(false);

        enfProntuario.setText("Prontuario");
        enfProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfProntuarioActionPerformed(evt);
            }
        });

        try {
            enfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(enfCronicabox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(enfHipertensaobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(enfRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(enfSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(enfTiposanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(enfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(enfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(348, 348, 348)
                                                .addComponent(jLabel24))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel23)
                                                    .addComponent(enfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(99, 99, 99)
                                                .addComponent(enfData, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(enfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(jLabel11)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(enfVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(enfProntuario)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(enfCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(enfEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(enfNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(enfSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(enfSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(enfCirurgiabox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(enfRemediobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(enfAlergiabox, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(jLabel10)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(enfDiabetebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(enfCardiacabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(enfCancerbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enfVerificar)
                            .addComponent(enfSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enfCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enfProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enfEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enfNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enfSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 59, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel26))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enfSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enfRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enfTiposanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enfCancerbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enfDiabetebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enfRemediobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enfCirurgiabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enfHipertensaobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enfCardiacabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(enfAlergiabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enfCronicabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1120, 620);
    }// </editor-fold>//GEN-END:initComponents

    private void enfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enfNomeActionPerformed

    private void enfTiposanguineoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfTiposanguineoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enfTiposanguineoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        telaEnfermariaPrincipal.cadastro=true;
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void enfSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfSairActionPerformed
        telaEnfermariaPrincipal.cadastro=false;
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_enfSairActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        telaEnfermariaPrincipal.cadastro=false;
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void enfSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfSalvarActionPerformed
        objpes= new dadosEnfermaria();
        preencher_objetos();
        try {
            AE = new addEdit();
            
                    if(acao==1){
                        AE.IncluirEnfermagem(objpes);
                        JOptionPane.showMessageDialog(this, "Salvo com sucesso !");
                        Salvar();
                    }  
                    if(acao==2){
                        objpes.setCpf(enfCpf.getText());
                        if(AE.EditarEnfermagem(objpes)){
                            JOptionPane.showMessageDialog(this, "Alterado com sucesso !");
                            Salvar();
                        }
                        
                    }
        }catch(SQLException error){
           JOptionPane.showMessageDialog (this,"Operação Não Realizada."+error.getMessage());
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_enfSalvarActionPerformed

    private void enfNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfNovoActionPerformed
        acao=1;
        Novo();
        // TODO add your handling code here:
    }//GEN-LAST:event_enfNovoActionPerformed

    private void enfEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfEditarActionPerformed
        acao=2;
        Editar();
        // TODO add your handling code here:
    }//GEN-LAST:event_enfEditarActionPerformed

    private void enfVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfVerificarActionPerformed
//        objpes= new dadosEnfermaria();
       
       if(enfCpf.getText().equals("   .   .   -  ")){

                telaEnfermariaEnfermariaConsulta  objconsulta  =  new  telaEnfermariaEnfermariaConsulta();
                telaEnfermariaPrincipal.telaPrincipal.add(objconsulta);
                objconsulta.setVisible(true);
                telaEnfermariaPrincipal.telaPrincipal.setComponentZOrder(objconsulta,0);
       
     
       }
       else{
           objpes.setCpf(enfCpf.getText());
                    Sea=  new  search();
                    try{
                        
                        if(Sea.SearchEnfermaria(objpes)){
                            if((objpes !=  null)){
                                pesquisa();
                            }
                                
                            }
                        }catch(SQLException erro){
                            JOptionPane.showMessageDialog(this,"Erro ao Pesquisar"+  erro.getMessage());
                        }
                    }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_enfVerificarActionPerformed

    private void enfCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfCancelarActionPerformed
        Cancelar();
        // TODO add your handling code here:
    }//GEN-LAST:event_enfCancelarActionPerformed

    private void enfProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfProntuarioActionPerformed
        if(prontuario==false){ 
        telaEnfermariaProntuariosConsulta obj = new telaEnfermariaProntuariosConsulta();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_enfProntuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> enfAlergiabox;
    private javax.swing.JTextArea enfAlergiatexto;
    private javax.swing.JFormattedTextField enfAltura;
    private javax.swing.JButton enfCancelar;
    private javax.swing.JComboBox<String> enfCancerbox;
    private javax.swing.JTextArea enfCancertexto;
    private javax.swing.JComboBox<String> enfCardiacabox;
    private javax.swing.JTextArea enfCardiacatexto;
    private javax.swing.JComboBox<String> enfCirurgiabox;
    private javax.swing.JTextArea enfCirurgiatexto;
    private static javax.swing.JFormattedTextField enfCpf;
    private javax.swing.JComboBox<String> enfCronicabox;
    private javax.swing.JTextArea enfCronicatexto;
    private javax.swing.JFormattedTextField enfData;
    private javax.swing.JComboBox<String> enfDiabetebox;
    private javax.swing.JTextArea enfDiabetetexto;
    private javax.swing.JButton enfEditar;
    private javax.swing.JComboBox<String> enfHipertensaobox;
    private javax.swing.JTextArea enfHipertensaotexto;
    private javax.swing.JTextField enfNome;
    private javax.swing.JButton enfNovo;
    private javax.swing.JButton enfProntuario;
    private javax.swing.JComboBox<String> enfRaca;
    private javax.swing.JComboBox<String> enfRemediobox;
    private javax.swing.JTextArea enfRemediotexto;
    private javax.swing.JButton enfSair;
    private javax.swing.JButton enfSalvar;
    private javax.swing.JComboBox<String> enfSexo;
    private javax.swing.JComboBox<String> enfStatus;
    private javax.swing.JComboBox<String> enfTiposanguineo;
    private javax.swing.JButton enfVerificar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea5;
    // End of variables declaration//GEN-END:variables
 public void preencher_objetos(){
            objpes.setNome(enfNome.getText().trim());
            objpes.setData(enfData.getText());         
            objpes.setSexo((String) enfSexo.getSelectedItem());
            objpes.setRaca((String) enfRaca.getSelectedItem());
            objpes.setAltura(enfAltura.getText());
            objpes.setCpf(enfCpf.getText());
            objpes.setTiposanguineo((String) enfTiposanguineo.getSelectedItem());
            objpes.setTremediobox((String) enfRemediobox.getSelectedItem());
            objpes.setTremediotexto(enfRemediotexto.getText());
            objpes.setTcancerbox((String) enfCancerbox.getSelectedItem());
            objpes.setTcancertexto(enfCancertexto.getText());
            objpes.setThipertensaobox((String) enfHipertensaobox.getSelectedItem());
            objpes.setThipertensaotexto(enfHipertensaotexto.getText());
            objpes.setTdiabetebox((String) enfDiabetebox.getSelectedItem());
            objpes.setTdiabetetexto(enfDiabetetexto.getText());
            objpes.setTcardiacabox((String) enfCardiacabox.getSelectedItem());
            objpes.setTcardiacatexto(enfCardiacatexto.getText());
            objpes.setTcronicabox((String) enfCronicabox.getSelectedItem());
            objpes.setTcronicatexto(enfCronicatexto.getText());
            objpes.setTcirurgiabox((String) enfCirurgiabox.getSelectedItem());
            objpes.setTcirurgiatexto(enfCirurgiatexto.getText());
            objpes.setTalergiabox((String) enfAlergiabox.getSelectedItem());
            objpes.setTalergiatexto(enfAlergiatexto.getText());
            objpes.setStatus((String) enfStatus.getSelectedItem());
          
        
    }
        
   public void pesquisa(){
      
        if(objpes.getSexo().equals("Masculino")){
           enfSexo.setSelectedIndex(1); 
        }
        if(objpes.getSexo().equals("Feminino")){
           enfSexo.setSelectedIndex(2); 
        }
        if(objpes.getRaca().equals("Amarelo(a)")){
           enfRaca.setSelectedIndex(1); 
        }
        if(objpes.getRaca().equals("Branco(a)")){
           enfRaca.setSelectedIndex(2); 
        }
        if(objpes.getRaca().equals("Indígena")){
           enfRaca.setSelectedIndex(3); 
        }
        if(objpes.getRaca().equals("Negro(a)")){
           enfRaca.setSelectedIndex(4); 
        }
        if(objpes.getRaca().equals("Pardo(a)")){
           enfRaca.setSelectedIndex(5); 
        }
         if(objpes.getTremediobox().equals("Não")){
           enfRemediobox.setSelectedIndex(1); 
        }
        if(objpes.getTremediobox().equals("Sim")){
           enfRemediobox.setSelectedIndex(2); 
        }
        if(objpes.getTcancerbox().equals("Não")){
           enfCancerbox.setSelectedIndex(1); 
        }
        if(objpes.getTcancerbox().equals("Sim")){
           enfCancerbox.setSelectedIndex(2); 
        }
        if(objpes.getTcancerbox().equals("Familiar")){
           enfCancerbox.setSelectedIndex(3); 
        }
        if(objpes.getThipertensaobox().equals("Não")){
           enfHipertensaobox.setSelectedIndex(1); 
        }
        if(objpes.getThipertensaobox().equals("Sim")){
           enfHipertensaobox.setSelectedIndex(2); 
        }
        if(objpes.getThipertensaobox().equals("Familiar")){
           enfHipertensaobox.setSelectedIndex(3); 
        }
         if(objpes.getTdiabetebox().equals("Não")){
           enfDiabetebox.setSelectedIndex(1); 
        }
        if(objpes.getTdiabetebox().equals("Sim")){
           enfDiabetebox.setSelectedIndex(2); 
        }
        if(objpes.getTdiabetebox().equals("Familiar")){
           enfDiabetebox.setSelectedIndex(3); 
        }
         if(objpes.getTcardiacabox().equals("Não")){
           enfCardiacabox.setSelectedIndex(1); 
        }
        if(objpes.getTcardiacabox().equals("Sim")){
           enfCardiacabox.setSelectedIndex(2); 
        }
        if(objpes.getTcardiacabox().equals("Familiar")){
           enfCardiacabox.setSelectedIndex(3); 
        }
         if(objpes.getTcronicabox().equals("Não")){
           enfCronicabox.setSelectedIndex(1); 
        }
        if(objpes.getTcronicabox().equals("Sim")){
           enfCronicabox.setSelectedIndex(2); 
        }
        if(objpes.getTcronicabox().equals("Familiar")){
           enfCronicabox.setSelectedIndex(3); 
        }
         if(objpes.getTcirurgiabox().equals("Não")){
           enfCirurgiabox.setSelectedIndex(1); 
        }
        if(objpes.getTcirurgiabox().equals("Sim")){
           enfCirurgiabox.setSelectedIndex(2); 
        }
        if(objpes.getTalergiabox().equals("Não")){
           enfAlergiabox.setSelectedIndex(1); 
        }
        if(objpes.getTalergiabox().equals("Sim")){
           enfAlergiabox.setSelectedIndex(2); 
        }
        if(objpes.getStatus().equals("Em atendimento")){
           enfStatus.setSelectedIndex(1); 
        }
        if(objpes.getStatus().equals("Não está mais em atendimento")){
           enfStatus.setSelectedIndex(2); 
        }
        if(objpes.getTiposanguineo().equals("A+")){
           enfTiposanguineo.setSelectedIndex(1); 
        }
        if(objpes.getTiposanguineo().equals("A-")){
           enfTiposanguineo.setSelectedIndex(2); 
        }
        if(objpes.getTiposanguineo().equals("B+")){
           enfTiposanguineo.setSelectedIndex(3); 
        }
        if(objpes.getTiposanguineo().equals("B-")){
           enfTiposanguineo.setSelectedIndex(4); 
        }
        if(objpes.getTiposanguineo().equals("AB+")){
           enfTiposanguineo.setSelectedIndex(5); 
        }
        if(objpes.getTiposanguineo().equals("AB-")){
           enfTiposanguineo.setSelectedIndex(6); 
        }
        if(objpes.getTiposanguineo().equals("O+")){
           enfTiposanguineo.setSelectedIndex(7); 
        }
        if(objpes.getTiposanguineo().equals("O-")){
           enfTiposanguineo.setSelectedIndex(8); 
        }
        
            
       
          enfNome.setText(objpes.getNome().trim());
          enfData.setText(objpes.getData());       
          enfAltura.setText(objpes.getAltura().trim()); 
          enfRemediotexto.setText(objpes.getTremediotexto().trim()); 
          enfCancertexto.setText(objpes.getTcancertexto().trim()); 
          enfHipertensaotexto.setText(objpes.getThipertensaotexto().trim()); 
          enfDiabetetexto.setText(objpes.getTdiabetetexto().trim()); 
          enfCardiacatexto.setText(objpes.getTcardiacatexto().trim()); 
          enfCronicatexto.setText(objpes.getTcronicatexto().trim()); 
          enfCirurgiatexto.setText(objpes.getTcirurgiatexto().trim()); 
          enfAlergiatexto.setText(objpes.getTalergiatexto().trim()); 
          enfStatus.setActionCommand(objpes.getStatus()); 
          enfEditar.setEnabled(true);
   } 
    

    public void Novo(){
        enfNome.setEnabled(true);
        enfData.setEnabled(true);
        enfSexo.setEnabled(true);
        enfRaca.setEnabled(true);
        enfAltura.setEnabled(true);
        enfCpf.setEnabled(true);
        enfTiposanguineo.setEnabled(true);
        enfRemediobox.setEnabled(true);
        enfRemediotexto.setEnabled(true);
        enfCancerbox.setEnabled(true);
        enfCancertexto.setEnabled(true);
        enfHipertensaobox.setEnabled(true);
        enfHipertensaotexto.setEnabled(true);
        enfDiabetebox.setEnabled(true);
        enfDiabetetexto.setEnabled(true);
        enfCardiacabox.setEnabled(true);
        enfCardiacatexto.setEnabled(true);
        enfCronicabox.setEnabled(true);
        enfCronicatexto.setEnabled(true);
        enfCirurgiabox.setEnabled(true);
        enfCirurgiatexto.setEnabled(true);
        enfAlergiabox.setEnabled(true);
        enfAlergiatexto.setEnabled(true);
        enfStatus.setEnabled(true);
        enfSalvar.setEnabled(true);
        enfEditar.setEnabled(true);
        
        enfNome.setText("");
        enfData.setText("");   
        enfAltura.setText("");   
        enfCpf.setText("");
        enfRemediotexto.setText("");
        enfCancertexto.setText("");
        enfHipertensaotexto.setText("");
        enfDiabetetexto.setText("");
        enfCardiacatexto.setText("");
        enfCronicatexto.setText("");
        enfCirurgiatexto.setText("");
        enfAlergiatexto.setText("");
        enfSexo.setSelectedIndex(0);
        enfRaca.setSelectedIndex(0);
        enfTiposanguineo.setSelectedIndex(0); 
        enfRemediobox.setSelectedIndex(0);
        enfCancerbox.setSelectedIndex(0);
        enfHipertensaobox.setSelectedIndex(0);
        enfDiabetebox.setSelectedIndex(0);
        enfCardiacabox.setSelectedIndex(0);
        enfCronicabox.setSelectedIndex(0);
        enfCirurgiabox.setSelectedIndex(0);
        enfAlergiabox.setSelectedIndex(0);
        enfStatus.setSelectedIndex(0);
    }

    public void Cancelar(){
        enfNome.setEnabled(false);
        enfData.setEnabled(false);
        enfSexo.setEnabled(false);
        enfRaca.setEnabled(false);
        enfAltura.setEnabled(false);
        enfTiposanguineo.setEnabled(false);
        enfRemediobox.setEnabled(false);
        enfRemediotexto.setEnabled(false);
        enfCancerbox.setEnabled(false);
        enfCancertexto.setEnabled(false);
        enfHipertensaobox.setEnabled(false);
        enfHipertensaotexto.setEnabled(false);
        enfDiabetebox.setEnabled(false);
        enfDiabetetexto.setEnabled(false);
        enfCardiacabox.setEnabled(false);
        enfCardiacatexto.setEnabled(false);
        enfCronicabox.setEnabled(false);
        enfCronicatexto.setEnabled(false);
        enfCirurgiabox.setEnabled(false);
        enfCirurgiatexto.setEnabled(false);
        enfAlergiabox.setEnabled(false);
        enfAlergiatexto.setEnabled(false);
        enfStatus.setEnabled(false);
        enfSalvar.setEnabled(false);
        enfEditar.setEnabled(false);
        enfNome.setText("");
        enfData.setText("");   
        enfAltura.setText("");   
        enfCpf.setText("");
        enfRemediotexto.setText("");
        enfCancertexto.setText("");
        enfHipertensaotexto.setText("");
        enfDiabetetexto.setText("");
        enfCardiacatexto.setText("");
        enfCronicatexto.setText("");
        enfCirurgiatexto.setText("");
        enfAlergiatexto.setText("");
        enfSexo.setSelectedIndex(0);
        enfRaca.setSelectedIndex(0);
        enfTiposanguineo.setSelectedIndex(0); 
        enfRemediobox.setSelectedIndex(0);
        enfCancerbox.setSelectedIndex(0);
        enfHipertensaobox.setSelectedIndex(0);
        enfDiabetebox.setSelectedIndex(0);
        enfCardiacabox.setSelectedIndex(0);
        enfCronicabox.setSelectedIndex(0);
        enfCirurgiabox.setSelectedIndex(0);
        enfAlergiabox.setSelectedIndex(0);
        enfStatus.setSelectedIndex(0);
}
public void Editar(){
        enfNome.setEnabled(true);
        enfData.setEnabled(true);
        enfSexo.setEnabled(true);
        enfRaca.setEnabled(true);
        enfAltura.setEnabled(true);
        enfCpf.setEnabled(true);
        enfTiposanguineo.setEnabled(true);
        enfRemediobox.setEnabled(true);
        enfRemediotexto.setEnabled(true);
        enfCancerbox.setEnabled(true);
        enfCancertexto.setEnabled(true);
        enfHipertensaobox.setEnabled(true);
        enfHipertensaotexto.setEnabled(true);
        enfDiabetebox.setEnabled(true);
        enfDiabetetexto.setEnabled(true);
        enfCardiacabox.setEnabled(true);
        enfCardiacatexto.setEnabled(true);
        enfCronicabox.setEnabled(true);
        enfCronicatexto.setEnabled(true);
        enfCirurgiabox.setEnabled(true);
        enfCirurgiatexto.setEnabled(true);
        enfAlergiabox.setEnabled(true);
        enfAlergiatexto.setEnabled(true);
        enfStatus.setEnabled(true);
        enfSalvar.setEnabled(true);
        enfEditar.setEnabled(true);
}
public void Salvar(){
        enfNome.setEnabled(false);
        enfData.setEnabled(false);
        enfSexo.setEnabled(false);
        enfRaca.setEnabled(false);
        enfAltura.setEnabled(false);
        enfTiposanguineo.setEnabled(false);
        enfRemediobox.setEnabled(false);
        enfRemediotexto.setEnabled(false);
        enfCancerbox.setEnabled(false);
        enfCancertexto.setEnabled(false);
        enfHipertensaobox.setEnabled(false);
        enfHipertensaotexto.setEnabled(false);
        enfDiabetebox.setEnabled(false);
        enfDiabetetexto.setEnabled(false);
        enfCardiacabox.setEnabled(false);
        enfCardiacatexto.setEnabled(false);
        enfCronicabox.setEnabled(false);
        enfCronicatexto.setEnabled(false);
        enfCirurgiabox.setEnabled(false);
        enfCirurgiatexto.setEnabled(false);
        enfAlergiabox.setEnabled(false);
        enfAlergiatexto.setEnabled(false);
        enfStatus.setEnabled(false);
        enfSalvar.setEnabled(false);
        enfEditar.setEnabled(true);
        

}

public static void recebecpf(dadosEnfermaria objpes){
    enfCpf.setText(objpes.getCpf());
    enfCpf.requestFocus();
}
}
