/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;


import Controller.dadosFarmacia;
import Model.addEdit;
import Model.delete;
import Model.search;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author uande
 */
public class telaFarmaciaFarmaciaCadastro extends javax.swing.JInternalFrame {

     int acao;   
    
    dadosFarmacia objpes =  new dadosFarmacia();
    addEdit  AE;
    search Sea;
    delete Del;
    public static boolean almoxarifado;
    public telaFarmaciaFarmaciaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        farSalvar = new javax.swing.JButton();
        farEditar = new javax.swing.JButton();
        farNovo = new javax.swing.JButton();
        farSair = new javax.swing.JButton();
        farCancelar = new javax.swing.JButton();
        farExcluir = new javax.swing.JButton();
        farCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        farProduto = new javax.swing.JTextField();

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jLabel13.setText("Toma algum rémedio ? Se sim qual?");

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        farSalvar.setText("Salvar");
        farSalvar.setEnabled(false);
        farSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farSalvarActionPerformed(evt);
            }
        });

        farEditar.setText("Editar");
        farEditar.setEnabled(false);
        farEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farEditarActionPerformed(evt);
            }
        });

        farNovo.setText("Novo");
        farNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farNovoActionPerformed(evt);
            }
        });

        farSair.setText("Sair");
        farSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farSairActionPerformed(evt);
            }
        });

        farCancelar.setText("Cancelar");
        farCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farCancelarActionPerformed(evt);
            }
        });

        farExcluir.setText("Excluir");
        farExcluir.setEnabled(false);
        farExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farExcluirActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        jLabel2.setText("Produto:");

        farProduto.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(farCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(farProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(farEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(farExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 160, Short.MAX_VALUE)
                                .addComponent(farSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(farSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(farCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(farNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(farCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(farProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(farEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(farExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farSair, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        setBounds(0, 0, 400, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void farSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farSairActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_farSairActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void farSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farSalvarActionPerformed
        objpes= new dadosFarmacia();
        preencher_objetos();
        try {
            AE = new addEdit();
            
                    if(acao==1){
                        AE.IncluirFarmacia(objpes);
                        JOptionPane.showMessageDialog(this, "Salvo com sucesso !");
                        Salvar();
                    }  
                    if(acao==2){
                        objpes.setCod(Integer.parseInt(farCodigo.getText()));
                        if(AE.EditarFarmacia(objpes)){
                            JOptionPane.showMessageDialog(this, "Alterado com sucesso !");
                            Salvar();
                        }
                        
                    }
        }catch(SQLException error){
           JOptionPane.showMessageDialog (this,"Operação Não Realizada."+error.getMessage());
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_farSalvarActionPerformed

    private void farNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farNovoActionPerformed
        acao=1;
        Novo();
        // TODO add your handling code here:
    }//GEN-LAST:event_farNovoActionPerformed

    private void farEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farEditarActionPerformed
        acao=2;
        Editar();
        // TODO add your handling code here:
    }//GEN-LAST:event_farEditarActionPerformed

    private void farCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farCancelarActionPerformed
        Cancelar();
        // TODO add your handling code here:
    }//GEN-LAST:event_farCancelarActionPerformed

    private void farExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farExcluirActionPerformed
        if (farCodigo.getText().equals(".   .   -")){
            JOptionPane.showMessageDialog(this,"Digite o CPF  :");
        }else{
            int Cod=Integer.parseInt(farCodigo.getText());
            
            Del  = new delete();
            try{
                if  (JOptionPane.showConfirmDialog(this,"Confirma a exclusao ?","Confirmação", JOptionPane.YES_NO_CANCEL_OPTION)  == JOptionPane.YES_OPTION){
                    
                    if(Del.DeleteFarmacia(Cod)){
                        JOptionPane.showMessageDialog(this,"Excluido  com sucesso ");
                        Cancelar();
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Erro ao excluir o cadastro ");
                    }
                    
                }
                else{
                    JOptionPane.showMessageDialog(this,"Operação concluida ");
                    Cancelar();
                }
            
        }catch( SQLException  error){
            JOptionPane.showMessageDialog(this,"Erro: Exclusão não realizada !" +error.getMessage());
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_farExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton farCancelar;
    private static javax.swing.JTextField farCodigo;
    private javax.swing.JButton farEditar;
    private javax.swing.JButton farExcluir;
    private javax.swing.JButton farNovo;
    private javax.swing.JTextField farProduto;
    private javax.swing.JButton farSair;
    private javax.swing.JButton farSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea5;
    // End of variables declaration//GEN-END:variables
 public void preencher_objetos(){
            objpes.setCod(Integer.parseInt(farCodigo.getText()));
            objpes.setProduto(farProduto.getText().trim());


    }
        
   public void pesquisa(){
          farProduto.setText(objpes.getProduto().trim());
          farEditar.setEnabled(true);
   } 
    

    public void Novo(){
        farProduto.setEnabled(true);
        farSalvar.setEnabled(true);
        farEditar.setEnabled(true);
        farCodigo.setEnabled(true);
        farProduto.setText("");
        farCodigo.setText("");

    }

    public void Cancelar(){
        farProduto.setEnabled(false);
        farSalvar.setEnabled(false);
        farEditar.setEnabled(false);
        farExcluir.setEnabled(false);
        farCodigo.setEnabled(false);
        farProduto.setText("");
        farCodigo.setText("");

}
public void Editar(){
        farProduto.setEnabled(true);
        farSalvar.setEnabled(true);
        farEditar.setEnabled(true);
        farCodigo.setEnabled(true);
        farExcluir.setEnabled(true);
}
public void Salvar(){
        farProduto.setEnabled(false);
        farSalvar.setEnabled(false);
        farEditar.setEnabled(true);
        farExcluir.setEnabled(false);
        farCodigo.setEnabled(false);
        

}

public static void recebecod(dadosFarmacia objpes){
    farCodigo.setText(String.valueOf(objpes.getCod()));
    farCodigo.requestFocus();
}
}
