package View;

import Model.addEdit;
import Model.delete;
import Model.search;
import Controller.dadosLogin;
import Controller.dadosRecepcao;
import Model.logEditarCadastro;
import Model.logIncluirCadastro;
import java.sql.SQLException;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author uande
 */
public class telaTICadastro extends javax.swing.JInternalFrame {

    int acao;   
   
     
    
    dadosRecepcao objpes =  new dadosRecepcao();
    addEdit  AE;
    delete Del;
    search Sea;
    
  
    public telaTICadastro() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cadNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cadSexo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cadCor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cadCivil = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cadEscolaridade = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cadData = new javax.swing.JFormattedTextField();
        cadCpf = new javax.swing.JFormattedTextField();
        cadSus = new javax.swing.JFormattedTextField();
        cadRg = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        cadTelProprio = new javax.swing.JFormattedTextField();
        cadTelConhecido = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        cadRua = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cadNum = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cadBairro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cadCep = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cadAdicional = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        cadCidade = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cadEstado = new javax.swing.JTextField();
        cadSalvar = new javax.swing.JButton();
        cadEditar = new javax.swing.JButton();
        cadSair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cadComplemento = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        cadPesquisa = new javax.swing.JButton();
        cadExcluir = new javax.swing.JButton();
        cadCancelar = new javax.swing.JButton();
        cadNovo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Pacientes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Nome Completo:");

        cadNome.setEnabled(false);
        cadNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Data de nascimento:");

        cadSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Masculino", "Feminino", " " }));
        cadSexo.setEnabled(false);
        cadSexo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadSexoMouseClicked(evt);
            }
        });
        cadSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadSexoActionPerformed(evt);
            }
        });

        jLabel3.setText("Sexo:");

        cadCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Amarelo(a)", "Branco(a)", "Indígena", "Negro(a)", "Pardo(a)" }));
        cadCor.setEnabled(false);

        jLabel4.setText("Cor/Raça");

        cadCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Casado(a)", "Divorciado(a)", "Separado(a)", "Solteiro(a)", "Viúvo(a)" }));
        cadCivil.setEnabled(false);

        jLabel5.setText("Estado Cívil:");

        jLabel6.setText("CPF:");

        jLabel7.setText("RG:");

        jLabel8.setText("Cartão do SUS:");

        cadEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Sem Instrução", "Ensino Fundamental Incompleto", "Ensino Fundamental Completo", "Ensino Médio Incompleto", "Ensino Médio Completo", "Ensino Superior Incompleto", "Ensino Superior Completo" }));
        cadEscolaridade.setEnabled(false);

        jLabel9.setText("Escolaridade:");

        try {
            cadData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cadData.setEnabled(false);

        try {
            cadCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cadSus.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.####.####.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cadSus.setEnabled(false);

        try {
            cadRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cadRg.setEnabled(false);

        jLabel10.setText("Telefone:");

        try {
            cadTelProprio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cadTelProprio.setEnabled(false);
        cadTelProprio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadTelProprioActionPerformed(evt);
            }
        });

        try {
            cadTelConhecido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cadTelConhecido.setEnabled(false);
        cadTelConhecido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadTelConhecidoActionPerformed(evt);
            }
        });

        jLabel11.setText("Telefone de Conhecido:");

        cadRua.setEnabled(false);

        jLabel12.setText("Rua:");

        cadNum.setEnabled(false);

        jLabel13.setText("Número:");

        jLabel14.setText("Bairro");

        cadBairro.setEnabled(false);

        jLabel15.setText("CEP:");

        try {
            cadCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cadCep.setEnabled(false);
        cadCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCepActionPerformed(evt);
            }
        });

        jLabel16.setText("Alguma informação adicional:");

        cadAdicional.setColumns(20);
        cadAdicional.setRows(5);
        cadAdicional.setEnabled(false);
        jScrollPane1.setViewportView(cadAdicional);

        jLabel17.setText("Cidade:");

        cadCidade.setEnabled(false);

        jLabel18.setText("Estado:");

        cadEstado.setEnabled(false);

        cadSalvar.setText("Salvar");
        cadSalvar.setEnabled(false);
        cadSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadSalvarActionPerformed(evt);
            }
        });

        cadEditar.setText("Editar");
        cadEditar.setEnabled(false);
        cadEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadEditarActionPerformed(evt);
            }
        });

        cadSair.setText("Sair");
        cadSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadSairActionPerformed(evt);
            }
        });

        cadComplemento.setColumns(20);
        cadComplemento.setRows(5);
        cadComplemento.setEnabled(false);
        jScrollPane2.setViewportView(cadComplemento);

        jLabel19.setText("Complemento:");

        cadPesquisa.setText("...");
        cadPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPesquisaActionPerformed(evt);
            }
        });

        cadExcluir.setText("Excluir");
        cadExcluir.setEnabled(false);
        cadExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadExcluirActionPerformed(evt);
            }
        });

        cadCancelar.setText("Cancelar");
        cadCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCancelarActionPerformed(evt);
            }
        });

        cadNovo.setText("Novo");
        cadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cadNome, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cadPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cadCidade)
                                .addGap(18, 18, 18)
                                .addComponent(cadEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(126, 126, 126)
                                .addComponent(jLabel11)
                                .addGap(0, 24, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadTelProprio, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(cadBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel17))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(cadTelConhecido, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cadCep, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cadEscolaridade, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(0, 121, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(cadData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cadCor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4))
                                                .addGap(16, 16, 16)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(cadSus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(32, 32, 32)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel13)
                                                        .addComponent(cadNum, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(cadRg, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(cadCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(cadRua, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cadSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                .addComponent(cadEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(cadSair, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cadExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cadNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cadCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(27, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cadNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadPesquisa)))
                    .addComponent(cadCpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jLabel5))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadSus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cadEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadTelProprio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadTelConhecido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadSair, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        setBounds(300, 20, 765, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void cadSexoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadSexoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cadSexoMouseClicked

    private void cadSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadSexoActionPerformed

    private void cadTelProprioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadTelProprioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadTelProprioActionPerformed

    private void cadTelConhecidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadTelConhecidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadTelConhecidoActionPerformed

    private void cadCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadCepActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        telaTIPrincipal.cadastro=true;
        
      
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void cadSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadSairActionPerformed
        telaTIPrincipal.cadastro=false;
        
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_cadSairActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
         telaTIPrincipal.cadastro=false;
         
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void cadSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadSalvarActionPerformed
     
        objpes= new dadosRecepcao();
        preencher_objetos();
        try {
            AE = new addEdit();
            
                    if(acao==1){
                        AE.IncluirRecepcao(objpes);
                        addEdit objlog = new logIncluirCadastro();
                        objlog.IncluirLog(objpes);
                        JOptionPane.showMessageDialog(this, "Salvo com sucesso !");
                        Salvar();
                    }  
                    if(acao==2){
                        objpes.setCpf(cadCpf.getText());
                        if(AE.EditarRecepcao(objpes)){
                            addEdit objlog = new logEditarCadastro();
                             objlog.IncluirLog(objpes);
                            JOptionPane.showMessageDialog(this, "Alterado com sucesso !");
                            Salvar();
                        }
                        
                    }
        }catch(SQLException error){
           JOptionPane.showMessageDialog (this,"Operação Não Realizada."+error.getMessage());
        }
        
    }//GEN-LAST:event_cadSalvarActionPerformed

    private void cadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadNovoActionPerformed
        acao=1;
        Novo();
        
    }//GEN-LAST:event_cadNovoActionPerformed

    private void cadCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCancelarActionPerformed
        Cancelar();
        
    }//GEN-LAST:event_cadCancelarActionPerformed

    private void cadEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadEditarActionPerformed
        acao=2;
        Editar();
        
    }//GEN-LAST:event_cadEditarActionPerformed

    private void cadNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadNomeActionPerformed

    private void cadExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadExcluirActionPerformed
            
        if (cadCpf.getText().equals(".   .   -")){
            JOptionPane.showMessageDialog(this,"Digite o CPF  :");
        }else{
            String CPF=cadCpf.getText();
            
            Del  = new delete();
            try{
                if  (JOptionPane.showConfirmDialog(this,"Confirma a exclusao ?","Confirmação", JOptionPane.YES_NO_CANCEL_OPTION)  == JOptionPane.YES_OPTION){
                    
                    if(Del.Delete(CPF)){
                        JOptionPane.showMessageDialog(this,"Excluido  com sucesso ");
                        Cancelar();
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Erro ao excluir o cadastro ");
                    }
                    
                }
                else{
                    JOptionPane.showMessageDialog(this,"Operação concluida ");
                    Cancelar();
                }
            
        }catch( SQLException  error){
            JOptionPane.showMessageDialog(this,"Erro: Exclusão não realizada !" +error.getMessage());
        }
        }
    }//GEN-LAST:event_cadExcluirActionPerformed

    private void cadPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPesquisaActionPerformed
       objpes= new dadosRecepcao();
       
       if(cadCpf.getText().equals("   .   .   -  ")){
               dadosLogin objpes = new dadosLogin();           
               telaTIConsulta  objconsulta  =  new  telaTIConsulta();
               telaTIPrincipal.telaPrincipal.add(objconsulta);
               objconsulta.setVisible(true);
               telaTIPrincipal.telaPrincipal.setComponentZOrder(objconsulta,0);
       
     
       }
       else{
           objpes.setCpf(cadCpf.getText());
                    Sea=  new  search();
                    try{
                        
                        if(Sea.SearchRecepcao(objpes)){
                            if((objpes !=  null)){
                                pesquisa();
                            }
                                
                            }
                        }catch(SQLException erro){
                            JOptionPane.showMessageDialog(this,"Erro ao Pesquisar"+  erro.getMessage());
                        }
                    }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_cadPesquisaActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cadAdicional;
    private javax.swing.JTextField cadBairro;
    private javax.swing.JButton cadCancelar;
    private javax.swing.JFormattedTextField cadCep;
    private javax.swing.JTextField cadCidade;
    private javax.swing.JComboBox<String> cadCivil;
    private javax.swing.JTextArea cadComplemento;
    private javax.swing.JComboBox<String> cadCor;
    private static javax.swing.JFormattedTextField cadCpf;
    private javax.swing.JFormattedTextField cadData;
    private javax.swing.JButton cadEditar;
    private javax.swing.JComboBox<String> cadEscolaridade;
    private javax.swing.JTextField cadEstado;
    private javax.swing.JButton cadExcluir;
    private javax.swing.JTextField cadNome;
    private javax.swing.JButton cadNovo;
    private javax.swing.JTextField cadNum;
    private javax.swing.JButton cadPesquisa;
    private javax.swing.JFormattedTextField cadRg;
    private javax.swing.JTextField cadRua;
    private javax.swing.JButton cadSair;
    private javax.swing.JButton cadSalvar;
    private javax.swing.JComboBox<String> cadSexo;
    private javax.swing.JFormattedTextField cadSus;
    private javax.swing.JFormattedTextField cadTelConhecido;
    private javax.swing.JFormattedTextField cadTelProprio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    public void preencher_objetos(){
            objpes.setNome(cadNome.getText().trim());
            objpes.setData(cadData.getText());
            objpes.setCep(cadCep.getText());
            objpes.setRua(cadRua.getText());
            objpes.setBairro(cadBairro.getText());
            objpes.setNumeroCasa(cadNum.getText());
            objpes.setComplemento(cadComplemento.getText());
            objpes.setCidade(cadCidade.getText());
            objpes.setEstado(cadEstado.getText());
            objpes.setTelefoneProprio(cadTelProprio.getText());
            objpes.setTelefoneConhecido(cadTelConhecido.getText());
            objpes.setSexo((String) cadSexo.getSelectedItem());
            objpes.setCor((String) cadCor.getSelectedItem());
            objpes.setCivil((String) cadCivil.getSelectedItem());
            objpes.setCpf(cadCpf.getText());
            objpes.setRg(cadRg.getText());
            objpes.setEscolaridade((String) cadEscolaridade.getSelectedItem());
            objpes.setSus(cadSus.getText());
            objpes.setAdicional(cadAdicional.getText());
        
    }
        
   public void pesquisa(){
      
        if(objpes.getSexo().equals("Masculino")){
           cadSexo.setSelectedIndex(1); 
        }
        if(objpes.getSexo().equals("Feminino")){
           cadSexo.setSelectedIndex(2); 
        }
        if(objpes.getCivil().equals("Casado(a)")){
           cadCivil.setSelectedIndex(1); 
        }
        if(objpes.getCivil().equals("Divorciado(a)")){
           cadCivil.setSelectedIndex(2); 
        }
        if(objpes.getCivil().equals("Separado(a)")){
           cadCivil.setSelectedIndex(3); 
        }
        if(objpes.getCivil().equals("Solteiro(a)")){
           cadCivil.setSelectedIndex(4); 
        }
        if(objpes.getCivil().equals("Viúvo(a)")){
           cadCivil.setSelectedIndex(5); 
        }
        if(objpes.getEscolaridade().equals("Sem Instrução")){
           cadEscolaridade.setSelectedIndex(1); 
        }
        if(objpes.getEscolaridade().equals("Ensino Fundamental Incompleto")){
           cadEscolaridade.setSelectedIndex(2); 
        }
        if(objpes.getEscolaridade().equals("Ensino Fundamental Completo")){
           cadEscolaridade.setSelectedIndex(3); 
        }
        if(objpes.getEscolaridade().equals("Ensino Médio Incompleto")){
           cadEscolaridade.setSelectedIndex(4); 
        }
        if(objpes.getEscolaridade().equals("Ensino Médio Completo")){
           cadEscolaridade.setSelectedIndex(5); 
        }
        if(objpes.getEscolaridade().equals("Ensino Superior Incompleto")){
           cadEscolaridade.setSelectedIndex(6); 
        }
        if(objpes.getEscolaridade().equals("Ensino Superior Completo")){
           cadEscolaridade.setSelectedIndex(7); 
        }
        if(objpes.getCor().equals("Amarelo(a)")){
           cadCor.setSelectedIndex(1); 
        }
        if(objpes.getCor().equals("Branco(a)")){
           cadCor.setSelectedIndex(2); 
        }
        if(objpes.getCor().equals("Indígena")){
           cadCor.setSelectedIndex(3); 
        }
        if(objpes.getCor().equals("Negro(a)")){
           cadCor.setSelectedIndex(4); 
        }
        if(objpes.getCor().equals("Pardo(a)")){
           cadCor.setSelectedIndex(5); 
        }
            
       
          cadNome.setText(objpes.getNome().trim());
          cadData.setText(objpes.getData());       
          cadCep.setText(objpes.getCep().trim()); 
          cadRua.setText(objpes.getRua().trim()); 
          cadBairro.setText(objpes.getBairro().trim()); 
          cadNum.setText(objpes.getNumeroCasa().trim()); 
          cadComplemento.setText(objpes.getComplemento().trim()); 
          cadCidade.setText(objpes.getCidade().trim()); 
          cadEstado.setText(objpes.getEstado().trim()); 
          cadTelProprio.setText(objpes.getTelefoneProprio().trim()); 
          cadTelConhecido.setText(objpes.getTelefoneConhecido().trim()); 
          cadCor.setActionCommand(objpes.getCor()); 
          cadCivil.setActionCommand(objpes.getCivil()); 
          cadRg.setText(objpes.getRg().trim()); 
          cadEscolaridade.setActionCommand(objpes.getEscolaridade()); 
          cadSus.setText(objpes.getSus().trim()); 
          cadAdicional.setText(objpes.getAdicional().trim());     
          cadEditar.setEnabled(true);
   } 
    

    public void Novo(){
        cadNome.setEnabled(true);
        cadData.setEnabled(true);
        cadSexo.setEnabled(true);
        cadCivil.setEnabled(true);
        cadEscolaridade.setEnabled(true);
        cadCor.setEnabled(true);
        cadSus.setEnabled(true);
        cadRg.setEnabled(true);
        cadTelProprio.setEnabled(true);
        cadTelConhecido.setEnabled(true);
        cadRua.setEnabled(true);
        cadNum.setEnabled(true);
        cadBairro.setEnabled(true);
        cadNum.setEnabled(true);
        cadCep.setEnabled(true);
        cadAdicional.setEnabled(true);
        cadCidade.setEnabled(true);
        cadEstado.setEnabled(true);
        cadComplemento.setEnabled(true);
        cadSalvar.setEnabled(true);
        cadEditar.setEnabled(true);
        cadCpf.setEnabled(true);
        cadNome.setText("");
        cadData.setText("");   
        cadSus.setText("");
        cadRg.setText("");
        cadTelProprio.setText("");
        cadTelConhecido.setText("");
        cadRua.setText("");
        cadNum.setText("");
        cadBairro.setText("");
        cadNum.setText("");
        cadCep.setText("");
        cadAdicional.setText("");
        cadCidade.setText("");
        cadEstado.setText("");
        cadComplemento.setText("");
        cadCpf.setText("");
        cadSexo.setSelectedIndex(0);
        cadCivil.setSelectedIndex(0);
        cadEscolaridade.setSelectedIndex(0);
        cadCor.setSelectedIndex(0);
    }

    public void Cancelar(){
        cadNome.setEnabled(false);
        cadData.setEnabled(false);
        cadSexo.setEnabled(false);
        cadCivil.setEnabled(false);
        cadEscolaridade.setEnabled(false);
        cadCor.setEnabled(false);
        cadSus.setEnabled(false);
        cadRg.setEnabled(false);
        cadTelProprio.setEnabled(false);
        cadTelConhecido.setEnabled(false);
        cadRua.setEnabled(false);
        cadNum.setEnabled(false);
        cadBairro.setEnabled(false);
        cadNum.setEnabled(false);
        cadCep.setEnabled(false);
        cadAdicional.setEnabled(false);
        cadCidade.setEnabled(false);
        cadEstado.setEnabled(false);
        cadComplemento.setEnabled(false);
        cadSalvar.setEnabled(false);
        cadEditar.setEnabled(false);
        cadExcluir.setEnabled(false);
        cadNome.setText("");
        cadData.setText("");   
        cadSus.setText("");
        cadRg.setText("");
        cadTelProprio.setText("");
        cadTelConhecido.setText("");
        cadRua.setText("");
        cadNum.setText("");
        cadBairro.setText("");
        cadNum.setText("");
        cadCep.setText("");
        cadAdicional.setText("");
        cadCidade.setText("");
        cadEstado.setText("");
        cadComplemento.setText("");
        cadCpf.setText("");
        cadSexo.setSelectedIndex(0);
        cadCivil.setSelectedIndex(0);
        cadEscolaridade.setSelectedIndex(0);
        cadCor.setSelectedIndex(0);
}
public void Editar(){
        cadNome.setEnabled(true);
        cadData.setEnabled(true);
        cadSexo.setEnabled(true);
        cadCivil.setEnabled(true);
        cadEscolaridade.setEnabled(true);
        cadCor.setEnabled(true);
        cadSus.setEnabled(true);
        cadRg.setEnabled(true);
        cadTelProprio.setEnabled(true);
        cadTelConhecido.setEnabled(true);
        cadRua.setEnabled(true);
        cadNum.setEnabled(true);
        cadBairro.setEnabled(true);
        cadNum.setEnabled(true);
        cadCep.setEnabled(true);
        cadAdicional.setEnabled(true);
        cadCidade.setEnabled(true);
        cadEstado.setEnabled(true);
        cadComplemento.setEnabled(true);
        cadSalvar.setEnabled(true);
        cadEditar.setEnabled(true);
        cadExcluir.setEnabled(true);
        cadCpf.setEnabled(true);
}
public void Salvar(){
        cadNome.setEnabled(false);
        cadData.setEnabled(false);
        cadSexo.setEnabled(false);
        cadCivil.setEnabled(false);
        cadEscolaridade.setEnabled(false);
        cadCor.setEnabled(false);
        cadSus.setEnabled(false);
        cadRg.setEnabled(false);
        cadTelProprio.setEnabled(false);
        cadTelConhecido.setEnabled(false);
        cadRua.setEnabled(false);
        cadNum.setEnabled(false);
        cadBairro.setEnabled(false);
        cadNum.setEnabled(false);
        cadCep.setEnabled(false);
        cadAdicional.setEnabled(false);
        cadCidade.setEnabled(false);
        cadEstado.setEnabled(false);
        cadComplemento.setEnabled(false);
        cadSalvar.setEnabled(false);
        cadEditar.setEnabled(true);
        cadExcluir.setEnabled(false);
        

}

public static void recebecpf(dadosRecepcao objpes){
    cadCpf.setText(objpes.getCpf());
    cadCpf.requestFocus();
}



}
