/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


/**
 *
 * @author uande
 */
public class telaEnfermariaPrincipal extends javax.swing.JFrame {
    public static boolean cadastro;
    public static boolean consulta;
    public static boolean enfermaria;
    public static boolean prontuario;
    public static boolean consultaEnfermaria;
    public static boolean almpedirProdutos;
    public static boolean farpedirProdutos;

    
    /**
     * Creates new form pjtPrincipal
     */
    public telaEnfermariaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        Enfermaria = new javax.swing.JMenuItem();
        consultaenfermaria = new javax.swing.JMenuItem();
        Prontuario = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        enfpedirprodutos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        farpedirprodutos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout telaPrincipalLayout = new javax.swing.GroupLayout(telaPrincipal);
        telaPrincipal.setLayout(telaPrincipalLayout);
        telaPrincipalLayout.setHorizontalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        telaPrincipalLayout.setVerticalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu3.setText("Enfermaria");

        Enfermaria.setText("Cadastro Enfermaria");
        Enfermaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnfermariaActionPerformed(evt);
            }
        });
        jMenu3.add(Enfermaria);

        consultaenfermaria.setText("Consulta Enfermaria");
        consultaenfermaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaenfermariaActionPerformed(evt);
            }
        });
        jMenu3.add(consultaenfermaria);

        Prontuario.setText("Prontuarios");
        Prontuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProntuarioActionPerformed(evt);
            }
        });
        jMenu3.add(Prontuario);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Almoxarifado");

        enfpedirprodutos.setText("Pedir Produtos");
        enfpedirprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfpedirprodutosActionPerformed(evt);
            }
        });
        jMenu1.add(enfpedirprodutos);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Farmacia");

        farpedirprodutos.setText("Pedir Produtos");
        farpedirprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farpedirprodutosActionPerformed(evt);
            }
        });
        jMenu4.add(farpedirprodutos);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
        telaEnfermariaPrincipal.cadastro=false;
        telaEnfermariaPrincipal.consulta=false;
        telaEnfermariaPrincipal.enfermaria=false;
        telaEnfermariaPrincipal.prontuario=false;
        telaEnfermariaPrincipal.consultaEnfermaria=false;
        telaEnfermariaPrincipal.almpedirProdutos=false;
        telaEnfermariaPrincipal.farpedirProdutos=false;
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void EnfermariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnfermariaActionPerformed
        if(enfermaria==false){ 
        telaEnfermariaEnfermaria obj = new telaEnfermariaEnfermaria();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_EnfermariaActionPerformed

    private void ProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProntuarioActionPerformed
         if(prontuario==false){ 
        telaEnfermariaProntuariosConsulta obj = new telaEnfermariaProntuariosConsulta();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ProntuarioActionPerformed

    private void consultaenfermariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaenfermariaActionPerformed
        if(consultaEnfermaria==false){ 
        telaEnfermariaEnfermariaConsulta obj = new telaEnfermariaEnfermariaConsulta();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaenfermariaActionPerformed

    private void enfpedirprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfpedirprodutosActionPerformed
        if(almpedirProdutos==false){ 
        telaEnfermariaAlmoxarifadoPedir obj = new telaEnfermariaAlmoxarifadoPedir();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_enfpedirprodutosActionPerformed

    private void farpedirprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farpedirprodutosActionPerformed
        if(farpedirProdutos==false){ 
        telaEnfermariaFarmaciaPedir obj = new telaEnfermariaFarmaciaPedir();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_farpedirprodutosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Enfermaria;
    private javax.swing.JMenuItem Prontuario;
    private javax.swing.JMenuItem consultaenfermaria;
    private javax.swing.JMenuItem enfpedirprodutos;
    private javax.swing.JMenuItem farpedirprodutos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JDesktopPane telaPrincipal;
    // End of variables declaration//GEN-END:variables
}
