/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;



/**
 *
 * @author uande
 */
public class telaTIPrincipal extends javax.swing.JFrame {
    public static boolean cadastro;
    public static boolean consulta;
    public static boolean cadastroUsuario;
    public static boolean consultaUsuario;
    public static boolean almcadastroProdutos;
    public static boolean exibirlog;
    public static boolean almexibirProdutos;
    public static boolean almpedirProdutos;
    public static boolean almsolicitacaoProdutos;
    public static boolean farcadastroProdutos;
    public static boolean farexibirProdutos;
    public static boolean farpedirProdutos;
    public static boolean farsolicitacaoProdutos;
    public static boolean enfermaria;
    public static boolean prontuario;
    public static boolean consultaEnfermaria;
    /**
     * Creates new form pjtPrincipal
     */
    public telaTIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        telaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadMenu = new javax.swing.JMenu();
        cadastrar = new javax.swing.JMenuItem();
        conMenu = new javax.swing.JMenu();
        Consultar = new javax.swing.JMenuItem();
        cadusuMenu = new javax.swing.JMenu();
        cadastrarusuario = new javax.swing.JMenuItem();
        Consultausuario = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        cadastrarprodutos = new javax.swing.JMenuItem();
        exibirprodutos = new javax.swing.JMenuItem();
        pedirprodutos = new javax.swing.JMenuItem();
        produtossolicitados = new javax.swing.JMenuItem();
        fsdfs = new javax.swing.JMenu();
        log = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        cadastroeenfermaria = new javax.swing.JMenuItem();
        consultaenfermaria = new javax.swing.JMenuItem();
        prontuarios = new javax.swing.JMenuItem();
        farmacia = new javax.swing.JMenu();
        farcadastrarprodutos = new javax.swing.JMenuItem();
        farexibirprodutos = new javax.swing.JMenuItem();
        farpedirprodutos = new javax.swing.JMenuItem();
        farprodutossolicitados = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout telaPrincipalLayout = new javax.swing.GroupLayout(telaPrincipal);
        telaPrincipal.setLayout(telaPrincipalLayout);
        telaPrincipalLayout.setHorizontalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        telaPrincipalLayout.setVerticalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        cadMenu.setText("Cadastro");

        cadastrar.setText("Cadastrar Paciente");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        cadMenu.add(cadastrar);

        jMenuBar1.add(cadMenu);

        conMenu.setText("Consultar");

        Consultar.setText("Consultar Paciente");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        conMenu.add(Consultar);

        jMenuBar1.add(conMenu);

        cadusuMenu.setText("Cadastro Usuário");

        cadastrarusuario.setText("Cadastrar Usuário");
        cadastrarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarusuarioActionPerformed(evt);
            }
        });
        cadusuMenu.add(cadastrarusuario);

        Consultausuario.setText("Consulta Usuário");
        Consultausuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultausuarioActionPerformed(evt);
            }
        });
        cadusuMenu.add(Consultausuario);

        jMenuBar1.add(cadusuMenu);

        jMenu1.setText("Almoxarifado");

        cadastrarprodutos.setText("Cadastrar Produtos");
        cadastrarprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarprodutosActionPerformed(evt);
            }
        });
        jMenu1.add(cadastrarprodutos);

        exibirprodutos.setText("Exibir Produtos");
        exibirprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirprodutosActionPerformed(evt);
            }
        });
        jMenu1.add(exibirprodutos);

        pedirprodutos.setText("Pedir Produtos");
        pedirprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirprodutosActionPerformed(evt);
            }
        });
        jMenu1.add(pedirprodutos);

        produtossolicitados.setText("Produtos Solicitados");
        produtossolicitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtossolicitadosActionPerformed(evt);
            }
        });
        jMenu1.add(produtossolicitados);

        jMenuBar1.add(jMenu1);

        fsdfs.setText("Log");

        log.setText("Exibir Log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        fsdfs.add(log);

        jMenuBar1.add(fsdfs);

        jMenu3.setText("Enfermaria");

        cadastroeenfermaria.setText("Cadastro Enfermaria");
        cadastroeenfermaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroeenfermariaActionPerformed(evt);
            }
        });
        jMenu3.add(cadastroeenfermaria);

        consultaenfermaria.setText("Consulta Enfermaria");
        consultaenfermaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaenfermariaActionPerformed(evt);
            }
        });
        jMenu3.add(consultaenfermaria);

        prontuarios.setText("Prontuarios");
        prontuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prontuariosActionPerformed(evt);
            }
        });
        jMenu3.add(prontuarios);

        jMenuBar1.add(jMenu3);

        farmacia.setText("Farmacia");

        farcadastrarprodutos.setText("Cadastrar Produtos");
        farcadastrarprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farcadastrarprodutosActionPerformed(evt);
            }
        });
        farmacia.add(farcadastrarprodutos);

        farexibirprodutos.setText("Exibir Produtos");
        farexibirprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farexibirprodutosActionPerformed(evt);
            }
        });
        farmacia.add(farexibirprodutos);

        farpedirprodutos.setText("Pedir Produtos");
        farpedirprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farpedirprodutosActionPerformed(evt);
            }
        });
        farmacia.add(farpedirprodutos);

        farprodutossolicitados.setText("Produtos Solicitados");
        farprodutossolicitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farprodutossolicitadosActionPerformed(evt);
            }
        });
        farmacia.add(farprodutossolicitados);

        jMenuBar1.add(farmacia);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
        telaTIPrincipal.cadastro=false;
        telaTIPrincipal.consulta=false;
        telaTIPrincipal.cadastroUsuario=false;
        telaTIPrincipal.consultaUsuario=false;
        telaTIPrincipal.exibirlog=false;
        telaTIPrincipal.almexibirProdutos=false;
        telaTIPrincipal.almpedirProdutos=false;
        telaTIPrincipal.almcadastroProdutos=false;
        telaTIPrincipal.almsolicitacaoProdutos=false;
        telaTIPrincipal.farexibirProdutos=false;
        telaTIPrincipal.farpedirProdutos=false;
        telaTIPrincipal.farcadastroProdutos=false;
        telaTIPrincipal.farsolicitacaoProdutos=false;
        telaTIPrincipal.enfermaria=false;
        telaTIPrincipal.prontuario=false;
        telaTIPrincipal.consultaEnfermaria=false;
        

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        if(cadastro==false){ 
        telaTICadastro obj = new telaTICadastro();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        if(consulta==false){ 
        telaTIConsulta obj = new telaTIConsulta();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarActionPerformed

    private void cadastrarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarusuarioActionPerformed
        if(cadastroUsuario==false){ 
        telaTILoginCadastro obj = new telaTILoginCadastro();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarusuarioActionPerformed

    private void ConsultausuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultausuarioActionPerformed
        if(consultaUsuario==false){ 
        telaTILoginConsulta obj = new telaTILoginConsulta();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultausuarioActionPerformed

    private void cadastrarprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarprodutosActionPerformed
         if(almcadastroProdutos==false){ 
        telaTIAlmoxarifadoCadastro obj = new telaTIAlmoxarifadoCadastro();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarprodutosActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        if(exibirlog==false){ 
        telaTIExibirLog obj = new telaTIExibirLog();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_logActionPerformed

    private void exibirprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirprodutosActionPerformed
        if(almcadastroProdutos==false){ 
        telaTIAlmoxarifadoConsulta obj = new telaTIAlmoxarifadoConsulta();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_exibirprodutosActionPerformed

    private void pedirprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirprodutosActionPerformed
        if(almpedirProdutos==false){ 
        telaTIAlmoxarifadoPedir obj = new telaTIAlmoxarifadoPedir();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_pedirprodutosActionPerformed

    private void produtossolicitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtossolicitadosActionPerformed
        if(almsolicitacaoProdutos==false){ 
        telaTIAlmoxarifadoPedidos obj = new telaTIAlmoxarifadoPedidos();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_produtossolicitadosActionPerformed

    private void cadastroeenfermariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroeenfermariaActionPerformed
        if(enfermaria==false){ 
        telaTIEnfermaria obj = new telaTIEnfermaria();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroeenfermariaActionPerformed

    private void prontuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prontuariosActionPerformed
        if(prontuario==false){ 
        telaTIProntuariosConsulta obj = new telaTIProntuariosConsulta();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_prontuariosActionPerformed

    private void consultaenfermariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaenfermariaActionPerformed
        if(consultaEnfermaria==false){ 
        telaTIEnfermariaConsulta obj = new telaTIEnfermariaConsulta();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaenfermariaActionPerformed

    private void farcadastrarprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farcadastrarprodutosActionPerformed
        if(farcadastroProdutos==false){ 
        telaTIFarmaciaCadastro obj = new telaTIFarmaciaCadastro();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_farcadastrarprodutosActionPerformed

    private void farexibirprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farexibirprodutosActionPerformed
        if(farexibirProdutos==false){ 
        telaTIFarmaciaConsulta obj = new telaTIFarmaciaConsulta();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_farexibirprodutosActionPerformed

    private void farpedirprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farpedirprodutosActionPerformed
        if(farpedirProdutos==false){ 
        telaTIFarmaciaPedir obj = new telaTIFarmaciaPedir();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_farpedirprodutosActionPerformed

    private void farprodutossolicitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farprodutossolicitadosActionPerformed
        if(farsolicitacaoProdutos==false){ 
        telaTIFarmaciaPedidos obj = new telaTIFarmaciaPedidos();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_farprodutossolicitadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Consultar;
    private javax.swing.JMenuItem Consultausuario;
    public static javax.swing.JMenu cadMenu;
    private javax.swing.JMenuItem cadastrar;
    private javax.swing.JMenuItem cadastrarprodutos;
    private javax.swing.JMenuItem cadastrarusuario;
    private javax.swing.JMenuItem cadastroeenfermaria;
    public static javax.swing.JMenu cadusuMenu;
    public static javax.swing.JMenu conMenu;
    private javax.swing.JMenuItem consultaenfermaria;
    private javax.swing.JMenuItem exibirprodutos;
    private javax.swing.JMenuItem farcadastrarprodutos;
    private javax.swing.JMenuItem farexibirprodutos;
    private javax.swing.JMenu farmacia;
    private javax.swing.JMenuItem farpedirprodutos;
    private javax.swing.JMenuItem farprodutossolicitados;
    private javax.swing.JMenu fsdfs;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem log;
    private javax.swing.JMenuItem pedirprodutos;
    private javax.swing.JMenuItem produtossolicitados;
    private javax.swing.JMenuItem prontuarios;
    public static javax.swing.JDesktopPane telaPrincipal;
    // End of variables declaration//GEN-END:variables

}
