/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Construct.dadosLogin;
import javax.swing.JOptionPane;

/**
 *
 * @author uande
 */
public class telaPrincipalTI extends javax.swing.JFrame {
    public static boolean cadastro;
    public static boolean consulta;
    public static boolean cadastroUsuario;
    /**
     * Creates new form pjtPrincipal
     */
    public telaPrincipalTI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        telaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadMenu = new javax.swing.JMenu();
        cadastrar = new javax.swing.JMenuItem();
        conMenu = new javax.swing.JMenu();
        Consultar = new javax.swing.JMenuItem();
        cadusuMenu = new javax.swing.JMenu();
        cadastrarusuario = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout telaPrincipalLayout = new javax.swing.GroupLayout(telaPrincipal);
        telaPrincipal.setLayout(telaPrincipalLayout);
        telaPrincipalLayout.setHorizontalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        telaPrincipalLayout.setVerticalGroup(
            telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        cadMenu.setText("Cadastro");

        cadastrar.setText("Cadastrar Paciente");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        cadMenu.add(cadastrar);

        jMenuBar1.add(cadMenu);

        conMenu.setText("Consultar");

        Consultar.setText("Consultar Paciente");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        conMenu.add(Consultar);

        jMenuBar1.add(conMenu);

        cadusuMenu.setText("Cadastro Usuário");

        cadastrarusuario.setText("Cadastrar Usuário");
        cadastrarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarusuarioActionPerformed(evt);
            }
        });
        cadusuMenu.add(cadastrarusuario);

        jMenuBar1.add(cadusuMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
        telaPrincipalTI.cadastro=false;
        telaPrincipalTI.consulta=false;
        telaPrincipalTI.cadastroUsuario=false;
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        if(cadastro==false){ 
        telaCadastroTI obj = new telaCadastroTI();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        if(consulta==false){ 
        telaConsultaRecepcao obj = new telaConsultaRecepcao();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarActionPerformed

    private void cadastrarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarusuarioActionPerformed
        if(cadastroUsuario==false){ 
        telaCadastroLogin obj = new telaCadastroLogin();
        telaPrincipal.add(obj);
        obj.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarusuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Consultar;
    public static javax.swing.JMenu cadMenu;
    private javax.swing.JMenuItem cadastrar;
    private javax.swing.JMenuItem cadastrarusuario;
    public static javax.swing.JMenu cadusuMenu;
    public static javax.swing.JMenu conMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JDesktopPane telaPrincipal;
    // End of variables declaration//GEN-END:variables
public static void recepcao(){
    cadMenu.setEnabled(false);
}
}
