/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import Connection.query;
import Construct.dadosRecepcao;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author uande
 */
public class telaConsultaRecepcao extends javax.swing.JInternalFrame {
    dadosRecepcao objpes= new dadosRecepcao();
    /**
     * Creates new form telaConsulta
     */
    public telaConsultaRecepcao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conVariavel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        conArgumento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        conTabela = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        conCapturar = new javax.swing.JButton();
        conSair = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Tela de Consulta");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        conVariavel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Nome", "CPF", "RG", "Cartão do SUS" }));

        jLabel1.setText("Consultar por :");

        conArgumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                conArgumentoKeyReleased(evt);
            }
        });

        conTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data de Nascimento", "CPF", "Telefone", "Telefone de conhecido", "Rua", "Bairro", "NúmCasa"
            }
        ));
        jScrollPane1.setViewportView(conTabela);
        if (conTabela.getColumnModel().getColumnCount() > 0) {
            conTabela.getColumnModel().getColumn(0).setPreferredWidth(40);
            conTabela.getColumnModel().getColumn(1).setMinWidth(100);
            conTabela.getColumnModel().getColumn(1).setMaxWidth(100);
            conTabela.getColumnModel().getColumn(2).setMinWidth(100);
            conTabela.getColumnModel().getColumn(2).setMaxWidth(100);
            conTabela.getColumnModel().getColumn(3).setMinWidth(110);
            conTabela.getColumnModel().getColumn(3).setMaxWidth(110);
            conTabela.getColumnModel().getColumn(4).setMinWidth(110);
            conTabela.getColumnModel().getColumn(4).setMaxWidth(110);
            conTabela.getColumnModel().getColumn(6).setMinWidth(130);
            conTabela.getColumnModel().getColumn(6).setMaxWidth(130);
            conTabela.getColumnModel().getColumn(7).setMinWidth(60);
            conTabela.getColumnModel().getColumn(7).setMaxWidth(60);
        }

        jLabel2.setText("Argumento:");

        conCapturar.setText("Capturar");
        conCapturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conCapturarActionPerformed(evt);
            }
        });

        conSair.setText("Sair");
        conSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conArgumento, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(conCapturar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(conSair, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conArgumento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conCapturar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conSair, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1300, 468);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
        
        DefaultTableModel mp1  = (DefaultTableModel) conTabela.getModel();
        int l=mp1.getRowCount();
        
            if(l>0){
                    while(l>0){
                ((DefaultTableModel) conTabela.getModel()).removeRow(l-1);
                              l--;
            }
            }
            try{
                ResultSet   rs=  query.loadTable();
                DefaultTableModel mp  = (DefaultTableModel) conTabela.getModel();
                while(rs.next()){
                    String   Coluna0=rs.getString("nome").toString().trim();
                    String   Coluna1=rs.getString("data").toString().trim();
                    String   Coluna2=rs.getString("cpf").toString().trim();
                    String   Coluna3=rs.getString("telefoneproprio").toString().trim();
                    String   Coluna4=rs.getString("telefoneconhecido").toString().trim();
                    String   Coluna5=rs.getString("rua").toString().trim();
                    String   Coluna6=rs.getString("bairro").toString().trim();
                    String   Coluna7=rs.getString("numerocasa").toString().trim();
                    
                    mp.addRow(new String[]{Coluna0,Coluna1,Coluna2,Coluna3,Coluna4,Coluna5,Coluna6,Coluna7});
                    
                }
            }
                catch(SQLException erro){
                        JOptionPane.showMessageDialog(this, "Ocorreu um erro: "+erro,"Preencher Item",2);
                        }
                tamanhocolunas();
                conTabela.setAutoCreateRowSorter(true);
            
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
         
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void conSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conSairActionPerformed
        
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_conSairActionPerformed

    private void conCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conCapturarActionPerformed
        int row =  conTabela.getSelectedRow();        
        objpes.setCpf((String) conTabela.getValueAt(row,2));
        telaCadastroRecepcao.recebecpf(objpes);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_conCapturarActionPerformed

    private void conArgumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conArgumentoKeyReleased
       String tipo=" ";
       String escolha=conVariavel.getSelectedItem().toString().trim();
       

       if(escolha.equals("Nome")){
           tipo="  "+"nome";
       }
       if(escolha.equals("RG")){
           tipo="  "+"rg";
       }
       if(escolha.equals("CPF")){
           tipo="  "+"cpf";
       }
       String arg=conArgumento.getText().toUpperCase();
       
        DefaultTableModel mp1  = (DefaultTableModel) conTabela.getModel();
        int l=mp1.getRowCount();
       
       if(l>0){
                    while(l>0){
                ((DefaultTableModel) conTabela.getModel()).removeRow(l-1);
                              l--;
            }
            }
       
            try{
                ResultSet   rs=  query.loadTable(tipo,  arg);
                DefaultTableModel mp  = (DefaultTableModel) conTabela.getModel();
                while(rs.next()){
                    String   Coluna0=rs.getString("nome").toString().trim();
                    String   Coluna1=rs.getString("data").toString().trim();
                    String   Coluna2=rs.getString("cpf").toString().trim();
                    String   Coluna3=rs.getString("telefoneproprio").toString().trim();
                    String   Coluna4=rs.getString("telefoneconhecido").toString().trim();
                    String   Coluna5=rs.getString("rua").toString().trim();
                    String   Coluna6=rs.getString("bairro").toString().trim();
                    String   Coluna7=rs.getString("numerocasa").toString().trim();
                    
                    mp.addRow(new String[]{Coluna0,Coluna1,Coluna2,Coluna3,Coluna4,Coluna5,Coluna6,Coluna7});
                    
                }
            }
                catch(SQLException erro){
                        JOptionPane.showMessageDialog(this, "Ocorreu um erro: "+erro,"Preencher Item",2);
                        }
                tamanhocolunas();
                conTabela.setAutoCreateRowSorter(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_conArgumentoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField conArgumento;
    private javax.swing.JButton conCapturar;
    private javax.swing.JButton conSair;
    private javax.swing.JTable conTabela;
    private javax.swing.JComboBox<String> conVariavel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
public void tamanhocolunas(){
conTabela.getColumnModel().getColumn(0).setMinWidth(100);
conTabela.getColumnModel().getColumn(1).setMinWidth(250);
}


}



